### ISSUE TITLE
Fabric Loader Problems

### ISSUE THREAD

**Issue by freeant72** [Iunius118/ChiliBulletWeapons#2]
I installed it to play the game with Fabric 1.20.1, but I get a log saying
 'Replace mod 'Fabric Loader' (fabricloader) 0.15.6 with version 0.15.7 or later'.  
However, my Fabric Loader is currently the highest version of 1.20.1 

And is not compatible with all the mods that can be done with Fabric at the moment (which are posted by the modders of this mod on Curseforge).   

So, I want to run this mode on this 1.20.1 fabric.
(It may seem strange because you are using a translator. I'm sorry. :->)

**Comment by freeant72** [comment]
upgrade to 1.20.2 is can't be to play my world..

**Comment by Iunius118** [comment]
The current version of this mod requires Fabric loader version 0.15.7. Please try to play on an instance with Fabric loader version 0.15.7 installed.

However, since there was little need to limit the loader to 0.15.7, the loader version restriction will be loosened in the next version.

**Comment by Iunius118** [comment]
Please try version 1.2.2 for fabric.
